version: "3"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:5.7
    environment:
      MYSQL_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_ALLOW_EMPTY_PASSWORD: false
      MYSQL_DATABASE: merchantdb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3308:3306

#  postgress:
#    container_name: postgress
#    image: postgress:alpine
#    ports:
#      - 5432:5432
#    environment:
#      POSTGRESS_PASSWORD:
#      POSTGRESS_DB: merchantdb


  springboot-app:
    image: springboot-app
    build: .
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: admin
      MYSQL_PASS: root
      MYSQL_PORT: 3306
      MYSQL_DATABASE: merchantdb

    depends_on:
      - mysqldb
    links:
      - mysqldb

#    restart: on-failure
